#!/bin/bash
notFirst="${BASH_SOURCE[0]}"
notFirst="${notFirst:0:${#notFirst}-8}/notFirst"
if ! [ -f $notFirst ] ; then
       echo "Root permission are required to perform upgrade"
       echo "For packages manager such as apt dnf snap"
       echo "To skip press enter"
       touch $notFirst
fi

echo "Enter password "
exit | sudo su

clear

APT=$(command -v apt)
if [ ${#APT} -gt 0 ] ; then
echo "Updating apt"
       sudo apt update
       echo "Update complete"
       clear
       echo "Upgrading packages"
       sudo apt upgrade -y
       clear
       echo "Clean Task"
       sudo apt auto-remove
       sudo apt auto-clean
       clear
fi

DNF=$(command -v dnf)

if [ ${#DNF} -gt 0 ] ; then
       echo "Updating dnf"
       sudo dnf upgrade -y
       echo "Update complete"
       clear
fi

SNAP=$(command -v snap)

if [ ${#SNAP} -gt 0 ] ; then
       echo "Updating snap"
       sudo snap update -y
       echo "Update complete"
       clear
fi

PACMAN=$(command -v pacman)

if [ ${#PACMAN} -gt 0 ] ; then
       echo "Updating pacman"
       sudo pacman -Syu
       echo "Update complete"
       clear
fi

FlATPAK=$(command -v flatpak)

if [ ${#FlATPAK} -gt 0 ] ; then
       echo "Updating flatpaks"
       flatpak update -y
       echo "Update complete"
       clear
fi


NEOFETCH=$(command -v neofetch)
if [ ${#FlATPAK} -gt 0 ] ; then
       neofetch
fi
